spring:
  profiles:
    active: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jpost
    username: heanzy.zabala
    password: ''

  jpa:
    hibernate:
      ddl-auto: validate

